// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: competition_account_requests.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCompetitionAccountRequest = `-- name: CreateCompetitionAccountRequest :exec
INSERT INTO competition_account_requests (
    user_id, competition_id
) VALUES ($1, $2)
ON CONFLICT (user_id, competition_id) DO NOTHING
`

type CreateCompetitionAccountRequestParams struct {
	UserID        uuid.UUID `db:"user_id" json:"user_id"`
	CompetitionID uuid.UUID `db:"competition_id" json:"competition_id"`
}

func (q *Queries) CreateCompetitionAccountRequest(ctx context.Context, arg CreateCompetitionAccountRequestParams) error {
	_, err := q.db.Exec(ctx, createCompetitionAccountRequest, arg.UserID, arg.CompetitionID)
	return err
}
