// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: competitions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCompetition = `-- name: CreateCompetition :one
INSERT INTO competitions (
    id, name, starts_at, ends_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, starts_at, ends_at, created_at
`

type CreateCompetitionParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Name     string    `db:"name" json:"name"`
	StartsAt time.Time `db:"starts_at" json:"starts_at"`
	EndsAt   time.Time `db:"ends_at" json:"ends_at"`
}

func (q *Queries) CreateCompetition(ctx context.Context, arg CreateCompetitionParams) (Competition, error) {
	row := q.db.QueryRow(ctx, createCompetition,
		arg.ID,
		arg.Name,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCompetitionByID = `-- name: GetCompetitionByID :one
SELECT id, name, starts_at, ends_at, created_at FROM competitions
WHERE id = $1
`

func (q *Queries) GetCompetitionByID(ctx context.Context, id uuid.UUID) (Competition, error) {
	row := q.db.QueryRow(ctx, getCompetitionByID, id)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCompetitionStartTime = `-- name: GetCompetitionStartTime :one
SELECT starts_at
FROM competitions
WHERE id = $1
`

func (q *Queries) GetCompetitionStartTime(ctx context.Context, id uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, getCompetitionStartTime, id)
	var starts_at time.Time
	err := row.Scan(&starts_at)
	return starts_at, err
}

const getCompetitionUserState = `-- name: GetCompetitionUserState :one
SELECT
    EXISTS (
        SELECT 1
        FROM competition_account_requests car
        WHERE car.user_id = $1
        AND car.competition_id = $2
    ) AS has_requested_account,
    EXISTS (
        SELECT 1
        FROM competition_members cm
        JOIN trading_accounts ta ON ta.login = cm.trading_account_login
        WHERE ta.user_id = $1
        AND cm.competition_id = $2
    ) AS has_joined
`

type GetCompetitionUserStateParams struct {
	UserID        uuid.UUID `db:"user_id" json:"user_id"`
	CompetitionID uuid.UUID `db:"competition_id" json:"competition_id"`
}

type GetCompetitionUserStateRow struct {
	HasRequestedAccount bool `db:"has_requested_account" json:"has_requested_account"`
	HasJoined           bool `db:"has_joined" json:"has_joined"`
}

func (q *Queries) GetCompetitionUserState(ctx context.Context, arg GetCompetitionUserStateParams) (GetCompetitionUserStateRow, error) {
	row := q.db.QueryRow(ctx, getCompetitionUserState, arg.UserID, arg.CompetitionID)
	var i GetCompetitionUserStateRow
	err := row.Scan(&i.HasRequestedAccount, &i.HasJoined)
	return i, err
}

const getCurrentCompetition = `-- name: GetCurrentCompetition :one
SELECT id, name, starts_at, ends_at, created_at
FROM competitions
WHERE now() < ends_at
ORDER BY starts_at ASC
LIMIT 1
`

func (q *Queries) GetCurrentCompetition(ctx context.Context) (Competition, error) {
	row := q.db.QueryRow(ctx, getCurrentCompetition)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCompetitions = `-- name: ListCompetitions :many
SELECT id, name, starts_at, ends_at, created_at FROM competitions
ORDER BY starts_at DESC
`

func (q *Queries) ListCompetitions(ctx context.Context) ([]Competition, error) {
	rows, err := q.db.Query(ctx, listCompetitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Competition
	for rows.Next() {
		var i Competition
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
