// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: competition_members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getCompetitionMemberAccountSize = `-- name: GetCompetitionMemberAccountSize :one
SELECT account_size
FROM competition_members
WHERE competition_id = $1
AND trading_account_login = $2
`

type GetCompetitionMemberAccountSizeParams struct {
	CompetitionID       uuid.UUID `db:"competition_id" json:"competition_id"`
	TradingAccountLogin int64     `db:"trading_account_login" json:"trading_account_login"`
}

func (q *Queries) GetCompetitionMemberAccountSize(ctx context.Context, arg GetCompetitionMemberAccountSizeParams) (float64, error) {
	row := q.db.QueryRow(ctx, getCompetitionMemberAccountSize, arg.CompetitionID, arg.TradingAccountLogin)
	var account_size float64
	err := row.Scan(&account_size)
	return account_size, err
}

const joinCompetitionBeforeStart = `-- name: JoinCompetitionBeforeStart :one
INSERT INTO competition_members (
    competition_id, trading_account_login, account_size
)
SELECT
    $1, $2, 0
FROM competitions c
WHERE c.id = $1
AND now() < c.starts_at
RETURNING competition_id
`

type JoinCompetitionBeforeStartParams struct {
	CompetitionID       uuid.UUID `db:"competition_id" json:"competition_id"`
	TradingAccountLogin int64     `db:"trading_account_login" json:"trading_account_login"`
}

func (q *Queries) JoinCompetitionBeforeStart(ctx context.Context, arg JoinCompetitionBeforeStartParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, joinCompetitionBeforeStart, arg.CompetitionID, arg.TradingAccountLogin)
	var competition_id uuid.UUID
	err := row.Scan(&competition_id)
	return competition_id, err
}

const updateCompetitionMemberAccountSize = `-- name: UpdateCompetitionMemberAccountSize :exec
UPDATE competition_members
SET account_size = $3
WHERE competition_id = $1
AND trading_account_login = $2
`

type UpdateCompetitionMemberAccountSizeParams struct {
	CompetitionID       uuid.UUID `db:"competition_id" json:"competition_id"`
	TradingAccountLogin int64     `db:"trading_account_login" json:"trading_account_login"`
	AccountSize         float64   `db:"account_size" json:"account_size"`
}

func (q *Queries) UpdateCompetitionMemberAccountSize(ctx context.Context, arg UpdateCompetitionMemberAccountSizeParams) error {
	_, err := q.db.Exec(ctx, updateCompetitionMemberAccountSize, arg.CompetitionID, arg.TradingAccountLogin, arg.AccountSize)
	return err
}
