// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Competition struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	StartsAt  time.Time `db:"starts_at" json:"starts_at"`
	EndsAt    time.Time `db:"ends_at" json:"ends_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type CompetitionAccountRequest struct {
	UserID        uuid.UUID `db:"user_id" json:"user_id"`
	CompetitionID uuid.UUID `db:"competition_id" json:"competition_id"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
}

type CompetitionMember struct {
	CompetitionID       uuid.UUID `db:"competition_id" json:"competition_id"`
	TradingAccountLogin int64     `db:"trading_account_login" json:"trading_account_login"`
	AccountSize         float64   `db:"account_size" json:"account_size"`
}

type RefreshToken struct {
	ID        uuid.UUID `db:"id" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Token     string    `db:"token" json:"token"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	Revoked   bool      `db:"revoked" json:"revoked"`
}

type Trade struct {
	TradingAccountLogin int64     `db:"trading_account_login" json:"trading_account_login"`
	CompetitionID       uuid.UUID `db:"competition_id" json:"competition_id"`
	PositionID          int64     `db:"position_id" json:"position_id"`
	Symbol              string    `db:"symbol" json:"symbol"`
	Side                string    `db:"side" json:"side"`
	Volume              float64   `db:"volume" json:"volume"`
	OpenTime            time.Time `db:"open_time" json:"open_time"`
	CloseTime           time.Time `db:"close_time" json:"close_time"`
	OpenPrice           float64   `db:"open_price" json:"open_price"`
	ClosePrice          float64   `db:"close_price" json:"close_price"`
	Profit              float64   `db:"profit" json:"profit"`
	Commission          float64   `db:"commission" json:"commission"`
	Swap                float64   `db:"swap" json:"swap"`
	CreatedAt           time.Time `db:"created_at" json:"created_at"`
}

type TradingAccount struct {
	Login                     int64     `db:"login" json:"login"`
	UserID                    uuid.UUID `db:"user_id" json:"user_id"`
	Broker                    string    `db:"broker" json:"broker"`
	InvestorPasswordEncrypted string    `db:"investor_password_encrypted" json:"investor_password_encrypted"`
	CreatedAt                 time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID              uuid.UUID `db:"id" json:"id"`
	Email           string    `db:"email" json:"email"`
	Username        string    `db:"username" json:"username"`
	DiscordUsername string    `db:"discord_username" json:"discord_username"`
	PasswordHash    string    `db:"password_hash" json:"password_hash"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
}
