// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tracked_trades.sql

package sqlc

import (
	"context"
	"time"
)

const closeTrackedTrade = `-- name: CloseTrackedTrade :execrows
UPDATE tracked_trades
SET closed_at = $2
WHERE position_id = $1
`

type CloseTrackedTradeParams struct {
	PositionID int64      `db:"position_id" json:"position_id"`
	ClosedAt   *time.Time `db:"closed_at" json:"closed_at"`
}

func (q *Queries) CloseTrackedTrade(ctx context.Context, arg CloseTrackedTradeParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeTrackedTrade, arg.PositionID, arg.ClosedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTrackedTrade = `-- name: CreateTrackedTrade :exec
INSERT INTO tracked_trades (
    position_id,
    symbol,
    side,
    open_price,
    stop_loss,
    volume,
    opened_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (position_id) DO NOTHING
`

type CreateTrackedTradeParams struct {
	PositionID int64     `db:"position_id" json:"position_id"`
	Symbol     string    `db:"symbol" json:"symbol"`
	Side       string    `db:"side" json:"side"`
	OpenPrice  float64   `db:"open_price" json:"open_price"`
	StopLoss   *float64  `db:"stop_loss" json:"stop_loss"`
	Volume     float64   `db:"volume" json:"volume"`
	OpenedAt   time.Time `db:"opened_at" json:"opened_at"`
}

func (q *Queries) CreateTrackedTrade(ctx context.Context, arg CreateTrackedTradeParams) error {
	_, err := q.db.Exec(ctx, createTrackedTrade,
		arg.PositionID,
		arg.Symbol,
		arg.Side,
		arg.OpenPrice,
		arg.StopLoss,
		arg.Volume,
		arg.OpenedAt,
	)
	return err
}

const listTrackedTrades = `-- name: ListTrackedTrades :many
SELECT
    position_id,
    symbol,
    side,
    open_price,
    stop_loss,
    volume,
    opened_at,
    closed_at
FROM tracked_trades
ORDER BY opened_at ASC
`

type ListTrackedTradesRow struct {
	PositionID int64      `db:"position_id" json:"position_id"`
	Symbol     string     `db:"symbol" json:"symbol"`
	Side       string     `db:"side" json:"side"`
	OpenPrice  float64    `db:"open_price" json:"open_price"`
	StopLoss   *float64   `db:"stop_loss" json:"stop_loss"`
	Volume     float64    `db:"volume" json:"volume"`
	OpenedAt   time.Time  `db:"opened_at" json:"opened_at"`
	ClosedAt   *time.Time `db:"closed_at" json:"closed_at"`
}

func (q *Queries) ListTrackedTrades(ctx context.Context) ([]ListTrackedTradesRow, error) {
	rows, err := q.db.Query(ctx, listTrackedTrades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrackedTradesRow
	for rows.Next() {
		var i ListTrackedTradesRow
		if err := rows.Scan(
			&i.PositionID,
			&i.Symbol,
			&i.Side,
			&i.OpenPrice,
			&i.StopLoss,
			&i.Volume,
			&i.OpenedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
