// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: trading_accounts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTradingAccount = `-- name: CreateTradingAccount :one
INSERT INTO trading_accounts (
    login, user_id, broker, investor_password_encrypted                              
) VALUES (
    $1, $2, $3, $4          
) RETURNING login, user_id, broker, created_at
`

type CreateTradingAccountParams struct {
	Login                     int64     `db:"login" json:"login"`
	UserID                    uuid.UUID `db:"user_id" json:"user_id"`
	Broker                    string    `db:"broker" json:"broker"`
	InvestorPasswordEncrypted string    `db:"investor_password_encrypted" json:"investor_password_encrypted"`
}

type CreateTradingAccountRow struct {
	Login     int64     `db:"login" json:"login"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Broker    string    `db:"broker" json:"broker"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateTradingAccount(ctx context.Context, arg CreateTradingAccountParams) (CreateTradingAccountRow, error) {
	row := q.db.QueryRow(ctx, createTradingAccount,
		arg.Login,
		arg.UserID,
		arg.Broker,
		arg.InvestorPasswordEncrypted,
	)
	var i CreateTradingAccountRow
	err := row.Scan(
		&i.Login,
		&i.UserID,
		&i.Broker,
		&i.CreatedAt,
	)
	return i, err
}

const getTradingAccountByLogin = `-- name: GetTradingAccountByLogin :one
SELECT login, user_id, broker, created_at
FROM trading_accounts
WHERE login = $1
LIMIT 1
`

type GetTradingAccountByLoginRow struct {
	Login     int64     `db:"login" json:"login"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Broker    string    `db:"broker" json:"broker"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) GetTradingAccountByLogin(ctx context.Context, login int64) (GetTradingAccountByLoginRow, error) {
	row := q.db.QueryRow(ctx, getTradingAccountByLogin, login)
	var i GetTradingAccountByLoginRow
	err := row.Scan(
		&i.Login,
		&i.UserID,
		&i.Broker,
		&i.CreatedAt,
	)
	return i, err
}

const getTradingAccountByUserID = `-- name: GetTradingAccountByUserID :one
SELECT login, user_id, broker, investor_password_encrypted, created_at
FROM trading_accounts
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetTradingAccountByUserID(ctx context.Context, userID uuid.UUID) (TradingAccount, error) {
	row := q.db.QueryRow(ctx, getTradingAccountByUserID, userID)
	var i TradingAccount
	err := row.Scan(
		&i.Login,
		&i.UserID,
		&i.Broker,
		&i.InvestorPasswordEncrypted,
		&i.CreatedAt,
	)
	return i, err
}
