// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: trades.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertTrade = `-- name: InsertTrade :exec
INSERT INTO trades (
    trading_account_login, competition_id, position_id, symbol, side, volume, open_time, close_time, open_price, close_price, profit, commission, swap
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) ON CONFLICT (trading_account_login, position_id)
DO NOTHING
`

type InsertTradeParams struct {
	TradingAccountLogin int64     `db:"trading_account_login" json:"trading_account_login"`
	CompetitionID       uuid.UUID `db:"competition_id" json:"competition_id"`
	PositionID          int64     `db:"position_id" json:"position_id"`
	Symbol              string    `db:"symbol" json:"symbol"`
	Side                string    `db:"side" json:"side"`
	Volume              float64   `db:"volume" json:"volume"`
	OpenTime            time.Time `db:"open_time" json:"open_time"`
	CloseTime           time.Time `db:"close_time" json:"close_time"`
	OpenPrice           float64   `db:"open_price" json:"open_price"`
	ClosePrice          float64   `db:"close_price" json:"close_price"`
	Profit              float64   `db:"profit" json:"profit"`
	Commission          float64   `db:"commission" json:"commission"`
	Swap                float64   `db:"swap" json:"swap"`
}

func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) error {
	_, err := q.db.Exec(ctx, insertTrade,
		arg.TradingAccountLogin,
		arg.CompetitionID,
		arg.PositionID,
		arg.Symbol,
		arg.Side,
		arg.Volume,
		arg.OpenTime,
		arg.CloseTime,
		arg.OpenPrice,
		arg.ClosePrice,
		arg.Profit,
		arg.Commission,
		arg.Swap,
	)
	return err
}

const listTradesByAccountLogin = `-- name: ListTradesByAccountLogin :many
SELECT trading_account_login, competition_id, position_id, symbol, side, volume, open_time, close_time, open_price, close_price, profit, commission, swap, created_at FROM trades
WHERE trading_account_login = $1
ORDER BY close_time DESC
`

func (q *Queries) ListTradesByAccountLogin(ctx context.Context, tradingAccountLogin int64) ([]Trade, error) {
	rows, err := q.db.Query(ctx, listTradesByAccountLogin, tradingAccountLogin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.TradingAccountLogin,
			&i.CompetitionID,
			&i.PositionID,
			&i.Symbol,
			&i.Side,
			&i.Volume,
			&i.OpenTime,
			&i.CloseTime,
			&i.OpenPrice,
			&i.ClosePrice,
			&i.Profit,
			&i.Commission,
			&i.Swap,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
