// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
     email, username, discord_username, password_hash                   
) VALUES (
    $1, $2, $3, $4
) RETURNING id, email, username, discord_username, created_at, updated_at
`

type CreateUserParams struct {
	Email           string `db:"email" json:"email"`
	Username        string `db:"username" json:"username"`
	DiscordUsername string `db:"discord_username" json:"discord_username"`
	PasswordHash    string `db:"password_hash" json:"password_hash"`
}

type CreateUserRow struct {
	ID              uuid.UUID `db:"id" json:"id"`
	Email           string    `db:"email" json:"email"`
	Username        string    `db:"username" json:"username"`
	DiscordUsername string    `db:"discord_username" json:"discord_username"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.DiscordUsername,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DiscordUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, discord_username, password_hash, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DiscordUsername,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, discord_username, password_hash, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DiscordUsername,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsernameByTradingAccountLogin = `-- name: GetUsernameByTradingAccountLogin :one
SELECT u.username
FROM trading_accounts ta
JOIN users u ON u.id = ta.user_id
WHERE ta.login = $1
LIMIT 1
`

func (q *Queries) GetUsernameByTradingAccountLogin(ctx context.Context, login int64) (string, error) {
	row := q.db.QueryRow(ctx, getUsernameByTradingAccountLogin, login)
	var username string
	err := row.Scan(&username)
	return username, err
}
